name: 'Setup node-bun Environment'
description: 'Setup Node.js, Bun, and install dependencies'
inputs:
  node-version:
    description: 'Node.js version to set up'
    required: false
    default: 'latest'
  working-directory:
    description:
      'The directory to install dependencies in (if install-paths is empty)'
    required: false
    default: '.'
  install-paths:
    description:
      'Newline-separated paths to install dependencies in, relative to the
      workspace root'
    required: false
    default: ''
  install-args:
    description: 'Newline-separated Bun install arguments'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v7.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Bun and install dependencies
      uses: iamvikshan/.github/.github/actions/bun@main
      with:
        working-directory: ${{ inputs.working-directory }}
        install-paths: ${{ inputs.install-paths }}
        install-args: ${{ inputs.install-args }}
