name: "Setup node-bun Environment"
description: "Setup Node.js, Bun, and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: "latest"

    - name: Setup Bun and install dependencies
      uses: ./.github/actions/setup-bun
