name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
assignees:
  - vixshan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? (Type N/A if, well, not applicable)
      placeholder: v1.6.9
      value: "This is the version I am running!"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach screenshots or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct Agreement
      description: By submitting this issue, you agree to follow our [Code of Conduct](../.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: community-code-of-conduct
    attributes:
      label: Community Code of Conduct Agreement
      description: By submitting this request, you agree to follow our [Code of Conduct](../.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the Open Sauced Community Code of Conduct
          required: true
