name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
assignees:
  - iamvikshan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened, and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this issue to you?
      options:
        - Critical (Blocking my work)
        - High (Would significantly improve my workflow)
        - Medium (Would be nice to have)
        - Low (Just an idea)
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please confirm the following
      options:
        - label: I am using the latest version of the software
          required: true
        - label: I have searched for existing bugs that match this one
          required: true
        - label: I am willing to provide additional information if needed
          required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct Agreement
      description:
        By submitting this issue, you agree to follow our [Code of Conduct](../.github/CODE_OF_CONDUCT.md) and
        [CLA](../.github/CLA.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
