name: Feature Request
description: "Got a brilliant idea? Share it with us, and let's make magic happen!"
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - iamvikshan
body:
  - type: markdown
    attributes:
      value: |
        Hey there, innovator! Thanks for taking the time to suggest a new feature. Your ideas help us build something awesome together!

  - type: textarea
    id: problem-description
    attributes:
      label: What's the spark behind this idea?
      description: "Is your feature request related to a problem? Tell us what's bugging you!"
      placeholder: "I'm always frustrated when [...] I wish it could do this instead!"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Did you brainstorm other ways?
      description: "Have you thought of any alternative solutions or features? We'd love to hear them!"
      placeholder: "What other approaches have you considered? Lay it on us!"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How badly do you want this?
      description: "How important is this feature to you? Is it a game-changer or just a nice-to-have?"
      options:
        - Critical (Blocking my work — SOS!)
        - High (Would significantly improve my workflow)
        - Medium (Would be nice to have someday)
        - Low (Just an idea floating around)
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Double-checklist
      description: "Before we dive in, let's make sure everything's good to go."
      options:
        - label: I've searched for similar feature requests and didn't find a match
          required: true
        - label: I'm ready to share more info if needed (we might need your help!)
          required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Play nice pledge
      description: |
        By submitting this request, you agree to follow our [Code of Conduct](../.github/CODE_OF_CONDUCT.md) and
        [CLA](../.github/CLA.md). Let's keep things friendly and collaborative!
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
