name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Desired solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe how you would like this problem to be solved...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What other approaches have you thought about?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Would significantly improve my workflow)
        - Medium (Would be nice to have)
        - Low (Just an idea)
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that match this one
          required: true
        - label: I am willing to provide additional information if needed
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups about the feature request here.
      placeholder: You can drag and drop images here to include them.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/vixshan/.github/blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
