name: "Checkout repo and setup node-bun Environment for Semantic release"
description: "Checkout, Setup Node.js, Bun, and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Backup Original Project Dependencies
      shell: bash
      run: |
        # Backup existing package.json and bun.lockb if they exist
        if [ -f package.json ]; then
          cp package.json package.json.original-backup
        fi
        if [ -f bun.lockb ]; then
          cp bun.lockb bun.lockb.original-backup
        fi

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install specific dependencies
      shell: bash
      run: |
        echo '{
          "dependencies": {
          "@semantic-release/changelog": "^6.0.3",
          "@semantic-release/commit-analyzer": "^13.0.0",
          "@semantic-release/exec": "^6.0.3",
          "@semantic-release/git": "^10.0.1",
          "@semantic-release/github": "^11.0.1",
          "@semantic-release/npm": "^12.0.1",
          "@semantic-release/release-notes-generator": "^14.0.1",
          "conventional-changelog-conventionalcommits": "^8.0.0",
          "conventional-changelog-gitmoji": "^0.2.5",
          "semantic-release": "^24.2.0",
          "semantic-release-gitmoji": "^1.6.8"
          }
        }' > package.json
        bun i

    - name: Restore Original Project Dependencies
      shell: bash
      run: |
        # Restore original package.json if backup exists
        if [ -f package.json.original-backup ]; then
          mv package.json.original-backup package.json
        else
          # If no original exists, remove action's package.json
          rm package.json
        fi

        # Restore original bun.lockb if backup exists
        if [ -f bun.lockb.original-backup ]; then
          mv bun.lockb.original-backup bun.lockb
        else
          # If no original exists, remove action's bun.lockb
          rm -f bun.lockb
        fi
