name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if:
          (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign
          the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: "signatures/cla.json"
          path-to-document: "https://github.com/${{ github.repository_owner }}/.github/blob/main/.github/CLA.md" # e.g. a CLA or a DCO document
          branch: "main"
          allowlist: dependabot-preview[bot], dependabot[bot], *bot, bot*
          create-file-commit-message: ":wrench: Creating a file for storing CLA signatures"
          signed-commit-message: ":wrench: @$contributorName has signed the CLA in #$pullRequestNo"
          custom-notsigned-prcomment:
            "Thanks for your submission! We ask that $you sign our [Contributor License Agreement](https://github.com/${{
            github.repository_owner }}/.github/blob/main/.github/CLA.md) before we can accept your contribution. You can sign the
            CLA by adding a comment below using this text:"
          custom-allsigned-prcomment: "✍️ All contributors have signed the CLA"
