name: PR Agent (Gemini)

on:
  pull_request:
    types:
      [
        'opened',
        'reopened',
        'ready_for_review',
        'review_requested',
        'synchronize',
      ]
  issue_comment:
    types: [created]
  workflow_call:
    inputs:
      extra_config_url:
        type: string
        default: 'https://raw.githubusercontent.com/iamvikshan/.github/main/configs/.pr_agent.toml'
        required: false
    secrets:
      GEMINI:
        description: 'Preferred Gemini API key used by PR-Agent.'
        required: false
      GEMINI_TOKEN:
        description: 'Alternative/fallback Gemini API key.'
        required: false

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number ||
    github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  pr_agent_job:
    if:
      ${{ (github.event_name == 'pull_request' ||
      github.event.issue.pull_request) && github.actor != 'github-actions[bot]'
      && !contains(github.actor, '[bot]') }}

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        uses: The-PR-Agent/pr-agent@v0.36.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_AI_STUDIO.GEMINI_API_KEY:
            ${{ (secrets.GEMINI || secrets.GEMINI_TOKEN) }}
          PR_AGENT_EXTRA_CONFIG_URL:
            ${{ inputs.extra_config_url ||
            'https://raw.githubusercontent.com/iamvikshan/.github/main/configs/.pr_agent.toml'
            }}
          github_action_config.pr_actions:
            '["opened", "reopened", "ready_for_review", "review_requested",
            "synchronize"]'
